version: '3.0'

services:
  web:
    image: web_test
    restart: "no"
    build: ./web
    depends_on:
      - postgres
    environment:
      - FLASK_APP=run.py
      - FLASK_TEST=1
    volumes:
      - ./web/:/home/flask/app/web
    stdin_open: true
    tty: true

  postgres:
    image: db_test
    restart: "no"
    build:
        context: ./postgresql
        args:
          POSTGRES_DB: flask-db-test
    volumes:
      - db:/var/lib/postgresql
    expose:
      - "5432"

volumes:
    db:
