version: '3'

services:
  web:
    ports:
      - "5000:5000"
      # - "8000:8000" For NGINX
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
      - ./web/:/home/flask/app/web
    command: flask run --host=0.0.0.0
    # --port=8000 for NGINX

  postgres:
    ports:
      - "5432:5432"
