version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - static:/usr/src/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
      - static:/usr/src/app/web/project/static
    depends_on:
      - web

  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - db:/var/lib/postgresql
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=flask-db

volumes:
    static:
    db:
