version: '3.0'

services:
  web:
    image: web_test
    restart: "no"
    environment:
      - FLASK_APP=run.py
      - FLASK_TEST=1
    volumes:
      - ./web/:/home/flask/app/web
    stdin_open: true
    tty: true

  postgres:
    image: db_test
    container_name: db-test
    expose:
      - "5433"
    environment:
      - POSTGRES_DB=flask-db-test
    build:
        context: ./postgresql
        args:
          POSTGRES_DB: flask-db-test
    command: "-p 5433"
