"""empty message

Revision ID: 3c56fb336469
Revises: None
Create Date: 2018-03-11 19:40:32.105469

"""

# revision identifiers, used by Alembic.
revision = '3c56fb336469'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('so_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_id'])
    op.create_foreign_key(None, 'user', 'user', ['so_id'], ['user_id'])
    op.drop_column('user', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'so_id')
    ### end Alembic commands ###
